# 기본적으로 요약자료 라벨링(발표자료는 별도 수정 바람)
요약 자료
- '**/*.md'

# 조별 라벨링
1조:
- '**/1조/*.md'

2조:
- '**/2조/*.md'

# chapter01~08 라벨링
Chapter 01:
- ch1/*.md
Chapter 02:
- ch2/*.md
Chapter 03:
- ch3/*.md
Chapter 04:
- ch4/*.md
Chapter 05:
- ch5/*.md
Chapter 06:
- ch6/*.md
Chapter 07:
- ch7/*.md
Chapter 08:
- ch8/*.md

# 발표자료 라벨링
발표 자료:
- any: ['**/README.md', '**/readme.md']
  all: ['!./REAME.md']
